### ISSUE TITLE
Add Port support?

### ISSUE THREAD

**Issue by phye** [go-chi/hostrouter#4]
As is documented in `go doc http.Request.Host`, the `req.Host` can consist of the form "host:port", but your code does not handle this scenario properly.

**Comment by VojtechVitek** [comment]
Reproducer code?

**Comment by phye** [comment]
Refer to this test file for reproducer:

https://github.com/phye/hostrouter/blob/master/hostrouter_test.go

**Comment by VojtechVitek** [comment]
`"api.hello.com"` and `"api.hello.com:3333"` are two different hosts.

Imho, you should make the hostrouter handle the `"api.hello.com:3333"` host.

If you want to get rid of the `:3333` port locally, I recommend using a proxy/router, ie. https://github.com/containous/traefik.

**Comment by phye** [comment]
Thanks for your response. 
I was actually trying to simulate the same behavior with nginx, where you can have several `servers` listen on the same port, and nginx will perform different actions based on the `hostname` passed in request. 

By removing the port no from http.Request.Host, the behavior above can be easily achieved. Otherwise, that behavior is not possible without external tools since I cannot make the following function call.

```
http.ListenAndServe(":3333", routerA)
http.ListenAndServe(":3333", routerB)
```

**Comment by VojtechVitek** [comment]
I recommend using Traefik https://github.com/containous/traefik to forward :3333 and other ports to a single :80 port.

Or otherwise, listen on the specific port on your localhost:

```go
r := chi.NewRouter()
// set up routes

hr := hostrouter.New()
hr.Map("api.hello.com:3333", r)
hr.Map("api.world.com:3333", r)

http.ListenAndServe("0.0.0.0:3333", hr)
```
